[package]
name = "backend"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.14"
crc32fast = "1.3.2"
ic-cdk = "0.5.2"
ic-cdk-macros = "0.5.2"
ic-evm-sign = "0.1.3"
serde = "1"
sha2 = "0.10.6"
